; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
;monitor_port = COM5
monitor_port = COM14
;Anlage: COM5, Labor: COM14
monitor_speed = 115200
;upload_port = COM5
upload_port = COM14
;Anlage: COM5, Labor: COM14

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
  -DDEBUG_SERIAL
  -DBHF_DEBUG
  -DFS_DEBUG
  -DDEBUG_M1_TRACE_INPUTS=0
  -DDEBUG_M1_RESET_CAUSE=0

[env:megaatmega2560-bhf-test]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
  -DDEBUG_SERIAL
  -DBHF_DEBUG
  -DDEBUG_M1_TRACE_INPUTS=0
  -DDEBUG_M1_RESET_CAUSE=0

[env:megaatmega2560-weichen-test]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
  -DDEBUG_SERIAL
  -DDEBUG_M1_TRACE_INPUTS=0
  -DDEBUG_M1_RESET_CAUSE=0


[env:megaatmega2560-fs0-log]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
  -DFS_DEBUG
  -DFS_DEBUG_FS0_ONLY=1
  -DDEBUG_M1_SENSOR_S0_LOG=1
  -DDEBUG_M1_TRACE_INPUTS=0
  -DDEBUG_M1_RESET_CAUSE=0
  -DDEBUG_M1_RUECKMELDER_LOG=0
  -DDEBUG_M1_BOOT_LOG=0
  -DDEBUG_M1_SELFTEST_LOG=0

[env:megaatmega2560-crash-log]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
  -DDEBUG_SERIAL
  -DDEBUG_M1_TRACE_INPUTS=0
  -DDEBUG_M1_RESET_CAUSE=1
  -DDEBUG_M1_RUECKMELDER_LOG=0


